//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeTrackingDBEntities2 : DbContext
    {
        public TimeTrackingDBEntities2()
            : base("name=TimeTrackingDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PROJECT> PROJECTs { get; set; }
        public DbSet<WORKER> WORKERs { get; set; }
        public DbSet<WORKTIME> WORKTIMEs { get; set; }
        public DbSet<PROJECTTIMETOTAL> PROJECTTIMETOTALs { get; set; }
        public DbSet<WORKERTIMETOTAL> WORKERTIMETOTALs { get; set; }
    }
}
