//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKTIME
    {
        public int projectId { get; set; }
        public int workerId { get; set; }
        public int workTimeInDays { get; set; }
    
        public virtual PROJECT PROJECT { get; set; }
        public virtual WORKER WORKER { get; set; }
    }
}
